spring:
  cloud:
    config:
      label: local
      server:
        native:
          search-locations: classpath:spring-config-master/
        prefix: /config
  profiles:
    active: native
server:
  context-path: /registry
  port: 8888
security:
  basic:
    enabled: true
  user:
    name: config
    password: config
management:
  context-path: /admin
  security:
    enabled: true
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false