spring:
  cloud:
    config:
      server:
        prefix: /config
        git:
          uri: file:///c:/opt/config-repo/spring-config-master
  profiles:
    active: local
server:
  port: 8888
  context-path: /registry
security:
  basic:
    enabled: true
  user:
    name: config
    password: config
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
management:
  context-path: /admin
  security:
    enabled: true
    